version: '2'

services:
  web:
    build: .
    command:  >
      sh -c "
             python3 manage.py makemigrations website  &&
             python3 manage.py migrate --run-syncdb &&
             python3 manage.py runserver 0.0.0.0:8000  --insecure"
    image: kosten19/dochub
    volumes:
      - file_system_data:/home/moderator/documents/
      - dochub_logs:/home/moderator/logs/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
      
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=dochub

volumes:
  file_system_data:
  postgres_data:
  dochub_logs: